@iasHostname = https://saptfe.accounts.ondemand.com
@xsuaaHostname = https://covidapp-4l1ifcm7.authentication.eu10.hana.ondemand.com
@iasTokenEndpoint = /oauth2/token
@capiasClientId = 0df641d4-fc7c-404e-951f-06eaec363780
@codeChallenge = E8sZGg-49to1h5rPk5w6l0xKoMz5fhCTp_4Jm-tk3DA
@codeVerifier = L6Fglaw13U76NKjVmKV5JcnSiD6fhOzOvIzRQKnQOFM
@btpXsuaaClient = sb-covidApp%21t127663

@btpXsuaaSecret = 6XGEKaw7ix9oajcTVUFmY%2Bbvroo%3D
//@capEndpoint = https://technical-field-enablement-covidapp-4l1ifcm7-dev-covidapp-srv.cfapps.eu10.hana.ondemand.com
@capEndpoint = http://localhost:4004

@maxCertificate = HC1:6BF980%80T9WJWG.FKY*4GO0YLCCI3T/2N5QFBBBM3*70HS8FN0+SCHHQWY09ICI*JD97TK0F90KECTHGWJC0FDC:5AIA%G7X+AQB9746HS80:5BIB0A6WF6$A8SR6U46/6AVS87OAEL6M+ARCAI%6OG8.*8DK4WJCT3EHS8XJC%+DXJCCWENF6PF63W56L6846%JC QE/IAYJC5LEW34U3ET7DXC9 QE-ED8%E.JCBECB1A-:8$96646AL60A60S6Q$D.UDRYA 96NF6L/5QW6307KQE*709WEQDD+Q6TW6FA7C466KCN9E%961A6DL6FA7D46JPCT3E5JDOA7Y96*965W5Z57..DX%DZJC8/DYOAZKERED1$C  C5$C JC6/D9Z90AFJ$DXVDCECLPCG/DBVDVTA7Y8Y*8C+9HS8VIAI3DCWEMY9B7BUY9:S9NB8$PC5$CUZC$$5Y$527B0.4WTP9GIB.686LHAM:+955E%T6Y6E.0JSTFD$D75V5QCRO0YZK/-RV7W+-AZUQEJS0N3$*CJTPAGPB G7YLRBW.W0A2V0B2%4KEUG

###
# !Approach using PKCE!
###

# Can only be executed in browser!
https://saptfe.accounts.ondemand.com/oauth2/authorize?client_id=0df641d4-fc7c-404e-951f-06eaec363780&scope=openid&code_challenge=E8sZGg-49to1h5rPk5w6l0xKoMz5fhCTp_4Jm-tk3DA&code_challenge_method=S256&redirect_uri=http%3A%2F%2Flocalhost%2F&response_type=code&state=state

###

# @name getIasToken
POST {{iasHostname}}{{iasTokenEndpoint}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{capiasClientId}}
&code=5438402a5fea00448a368352b6e71f14
&redirect_uri=http://localhost/
&grant_type=authorization_code
&code_verifier={{codeVerifier}}

###

@refresh_token = {{getIasToken.response.body.$.refresh_token}}

# @name getRefreshToken
POST {{iasHostname}}{{iasTokenEndpoint}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{capiasClientId}}
&refresh_token={{refresh_token}}
&grant_type=refresh_token

###

@id_token = {{getIasToken.response.body.$.id_token}}

# @name getCapResults
GET {{capEndpoint}}/authenticated/Books
Authorization: Bearer {{id_token}}
### 

POST {{capEndpoint}}/rest/verification/decodeCertificateString
Authorization: Bearer {{id_token}}
Accept: application/json
Content-Type: application/json

{"certificateString": "{{maxCertificate}}", "country": "DE"}

###

GET {{capEndpoint}}/rest/verification/getAvailableCountries()
Authorization: Bearer {{id_token}}
Accept: application/json
Content-Type: application/json

###

DELETE {{capEndpoint}}/permissions/Permissions('D063937')

###

GET {{capEndpoint}}/permissions/Permissions

###

# @name doXsuaaTokenExchange

POST {{xsuaaHostname}}/oauth/token HTTP/1.1
Accept: application/json
Content-Type: application/x-www-form-urlencoded

client_id={{btpXsuaaClient}}
&client_secret={{btpXsuaaSecret}}
&grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
&response_type=token+id_token
&assertion={{id_token}}
